main: fr.napotwiixe.banpl.Main
version: 0.1
name: Ban-Plugin
author: NapoTwiixe
description: Plugin de Ban
commands:
  gban:
    description: ouvre le gui de bans
  gmute:
    description: ouvre le gui des mutes
  gkick:
    description: ouvre le gui des kicks